// <auto-generated />
namespace SisConv.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _23112017_3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_23112017_3));
        
        string IMigrationMetadata.Id
        {
            get { return "201711240114337_23112017_3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
