// <auto-generated />
namespace SisConv.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-beta1-60406")]
    public sealed partial class _18102017 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_18102017));
        
        string IMigrationMetadata.Id
        {
            get { return "201710182347002_18102017"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
