// <auto-generated />
namespace SisConv.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _11122017_2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_11122017_2));
        
        string IMigrationMetadata.Id
        {
            get { return "201712111731341_11122017_2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
