// <auto-generated />
namespace SisConv.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class documentos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(documentos));
        
        string IMigrationMetadata.Id
        {
            get { return "201808240641378_documentos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
