// <auto-generated />
namespace SisConv.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addOrgaoEmissor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addOrgaoEmissor));
        
        string IMigrationMetadata.Id
        {
            get { return "201804291640474_addOrgaoEmissor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
